include:
  - kafka.create_kafka_node_directory
  - kafka.download_kafka
  - kafka.extract_kafka
  - kafka.configure_kafka_rebel_1
  - kafka.create_kafka_logs_directory
  - kafka.kafka_heap_opts
  - kafka.start_kafka_server
  - kafka.create_kafka_topic
  - kafka.describe_kafka_topic
  - kafka.kafka_console_producer
  - kafka.kafka_console_consumer